name:                gift-matcher
version:             0.1.0.0
github:              "githubuser/gift-matcher"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/gift-matcher#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- containers

library:
  source-dirs: src

executables:
  gift-matcher-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gift-matcher
    - random-shuffle
    - random
    - split

tests:
  spec:
    main: Spec.hs
    defaults: hspec/hspec@master
    dependencies:
      - gift-matcher
