name: gift-matcher
version: 0.1.0.0
id: gift-matcher-0.1.0.0-5GiAjBmQ8AhB7n5SalkKAW
key: gift-matcher-0.1.0.0-5GiAjBmQ8AhB7n5SalkKAW
license: BSD-3-Clause
copyright: 2018 Author name here
maintainer: example@example.com
author: Author name here
homepage: https://github.com/githubuser/gift-matcher#readme
description:
    Please see the README on GitHub at <https://github.com/githubuser/gift-matcher#readme>
abi: 55a362696d7b20fc2af69dc01ddc7545
exposed: True
exposed-modules:
    Lib Person.Person
hidden-modules: Paths_gift_matcher
import-dirs: /Users/jyallop/Documents/gift-matcher/.stack-work/install/x86_64-osx/c291579f480bf0c3631d1f17c61cc2eebd86946cc181e0516ae65c54210453b9/8.4.4/lib/x86_64-osx-ghc-8.4.4/gift-matcher-0.1.0.0-5GiAjBmQ8AhB7n5SalkKAW
library-dirs: /Users/jyallop/Documents/gift-matcher/.stack-work/install/x86_64-osx/c291579f480bf0c3631d1f17c61cc2eebd86946cc181e0516ae65c54210453b9/8.4.4/lib/x86_64-osx-ghc-8.4.4/gift-matcher-0.1.0.0-5GiAjBmQ8AhB7n5SalkKAW
dynamic-library-dirs: /Users/jyallop/Documents/gift-matcher/.stack-work/install/x86_64-osx/c291579f480bf0c3631d1f17c61cc2eebd86946cc181e0516ae65c54210453b9/8.4.4/lib/x86_64-osx-ghc-8.4.4
data-dir: /Users/jyallop/Documents/gift-matcher/.stack-work/install/x86_64-osx/c291579f480bf0c3631d1f17c61cc2eebd86946cc181e0516ae65c54210453b9/8.4.4/share/x86_64-osx-ghc-8.4.4/gift-matcher-0.1.0.0
hs-libraries: HSgift-matcher-0.1.0.0-5GiAjBmQ8AhB7n5SalkKAW
depends:
    base-4.11.1.0 containers-0.5.11.0
    hspec-2.5.5-8IdyrrVFhluL3uOaIrjwSq
abi-depends: base-4.11.1.0=b368cab58fa51949d1638013a72f7adf
             containers-0.5.11.0=3a03e29a933c27106de8caad6a8dba89
             hspec-2.5.5-8IdyrrVFhluL3uOaIrjwSq=54ad6eb6b8d2b6fbc3f36cb126dac0ea
haddock-interfaces: /Users/jyallop/Documents/gift-matcher/.stack-work/install/x86_64-osx/c291579f480bf0c3631d1f17c61cc2eebd86946cc181e0516ae65c54210453b9/8.4.4/doc/gift-matcher-0.1.0.0/gift-matcher.haddock
haddock-html: /Users/jyallop/Documents/gift-matcher/.stack-work/install/x86_64-osx/c291579f480bf0c3631d1f17c61cc2eebd86946cc181e0516ae65c54210453b9/8.4.4/doc/gift-matcher-0.1.0.0
